SIM_DIR=RunRules/Simulation
DFE_DIR=RunRules/DFE
FILE=RunRules/Simulation/Makefile
LOGFILE=log.log

all: distclean
	make -C ${SIM_DIR}

clean:
	rm -f ${LOGFILE}
	rm -f core.*
	rm -rf CPUCode/debug*
	mv ${SIM_DIR}/include/Maxfiles.h ${SIM_DIR}/include/Maxfiles.h.bak
	rm -f ${SIM_DIR}/include/*.h
	mv ${SIM_DIR}/include/Maxfiles.h.bak ${SIM_DIR}/include/Maxfiles.h
	make -C ${SIM_DIR} clean

distclean: clean fpga_clean
	make -C ${SIM_DIR} distclean

fpga:
	make -C ${DFE_DIR}

fpga_clean:
	make -C ${DFE_DIR} clean distclean

go: all
	make -C ${SIM_DIR} runsim
