#!/usr/bin/env python

import os, sys
from sys import argv

import delitecommon

## a forwarder to the delite script in DELITE_HOME
def main():
    usage = "usage: %prog <dsl runner> [delite args]"

    if len(argv) < 2:
        exit("a dsl runner must be passed as an argument")

    dslRunner = argv[1]
    delitecommon.checkDeliteEnv()
    
    scala_major_id = delitecommon.scala_major_id
    script_home = delitecommon.script_home
    DELITE_HOME = delitecommon.DELITE_HOME

    cp = ""
    # add all managed libs 
    # caveat: scalatest pulls in some non-virtualized scala dependencies which conflict with the scala-virtualized versions
    jars = [os.path.join(d,f) for (d, n, fs) in os.walk(script_home + "/lib_managed/") if not (d.count("org.scala-lang") > 0 and d.count("virtualized") == 0) for f in fs]
    for j in jars:
        cp = cp + j + os.pathsep

    # Delite
    cp = cp + DELITE_HOME + "/runtime/target/" + scala_major_id + "/classes" + os.pathsep

    old_cp = os.getenv("CLASSPATH", "")
    os.putenv("CLASSPATH", old_cp + os.pathsep + cp)
    
    os.system(DELITE_HOME + "/bin/delite " + dslRunner + " " + " ".join(argv[2:len(argv)]))

if __name__ == "__main__":
    main()
